version: '3.8'

services:
  # 1. Database Service
  database-service:
    build: ./database
    container_name: my-db-container
    ports:
      - "27017:27017" # <--- Make sure this dash exists
    volumes:
      - db-data:/data/db # <--- Make sure this dash exists
    networks:
      - exam-network # <--- Make sure this dash exists

  # 2. Backend Service
  backend-service:
    build: ./backend
    container_name: my-backend-container
    ports:
      - "5000:5000"
    depends_on:
      - database-service
    networks:
      - exam-network

  # 3. Frontend Service
  frontend-service:
    build: ./frontend
    container_name: my-frontend-container
    ports:
      - "8080:80"
    depends_on:
      - backend-service
    networks:
      - exam-network

volumes:
  db-data:


networks:
  exam-network:
